# Generated by Django 4.1.7 on 2023-03-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('I', 'Important'), ('NI', 'Not Important'), ('VI', 'Very Important')], default='NI', max_length=2),
        ),
    ]
